In [2]:
import numpy as np

In [4]:
l1 = [1,2,3,4,5]
l2 = [6,7,8,9,10]
l3 = [11,12,13,14,15]
array1 = np.array([l1,l2,l3])
print(array1)
print(array1.ndim)
l4 = ['a','b','c','d','e']
l5 = ['f','g','h','k','l']
l6 = ['m','n','o','p','q']

array2 = np.array([[l1,l2,l3],[l4,l5,l6]]) 
print(array2)
print(array2.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
2
[[['1' '2' '3' '4' '5']
  ['6' '7' '8' '9' '10']
  ['11' '12' '13' '14' '15']]

 [['a' 'b' 'c' 'd' 'e']
  ['f' 'g' 'h' 'k' 'l']
  ['m' 'n' 'o' 'p' 'q']]]
3


In [8]:
print(array1[1][2])
#OR
print(array1[1,2])

8
8


In [7]:
#3D Array
l1 = [1,2,3,4,5]
l2 = [6,7,8,9,10]
l3 = [11,12,13,14,15]
l4 = [16,17,18,19,20]

array2 = np.array([[l1,l2],[l3,l4]])
print(array2)
print(array2[0, 1, 2])
print(array2.shape)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
8
(2, 2, 5)
