In [2]:
import numpy as np

In [6]:
l1 = [1,2,3,4,5]
l2 = [6,7,8,9,10]
l3 = [11,12,13,14,15]

array1 = np.array([l1,l2,l3]) 
print(array1)
print(array1.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
2


In [8]:
print(array1[1][2])
#OR
print(array1[1,2])

8
8


In [7]:
#3D Array
l1 = [1,2,3,4,5]
l2 = [6,7,8,9,10]
l3 = [11,12,13,14,15]
l4 = [16,17,18,19,20]

array2 = np.array([[l1,l2],[l3,l4]])
print(array2)
print(array2[0, 1, 2])
print(array2.shape)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
8
(2, 2, 5)
